### ISSUE TITLE
Is there any tutorials or jupyter notebook ?

### ISSUE THREAD

**Issue by lj-cug** [petroGG/petrophysics#2]
This is a good tool for well interpretation. But I cannot find any example or jupyter notebook to teach how to use it.
Could you give me some guide?
Li Jian

**Comment by Philliec459** [comment]
I too found this repository to be quite useful, so I created a Shaley Sand Analysis Jupyter Notebook example for the exact reason that you mention. This notebook can be found at the following GitHub link:

https://github.com/Philliec459/NEW-Shaley-Sand-Log-Analysis-Tutorial-using-Combined-NMR-and-Conventional-Logs

**Comment by Philliec459** [comment]
and a few more in this repository:

https://github.com/Philliec459/Older-Combined_NMR_Conventional_Logs-Shaley-Sand-Analysis-using-PetroGG

**Comment by petroGG** [comment]
> This is a good tool for well interpretation. But I cannot find any example or jupyter notebook to teach how to use it. Could you give me some guide? Li Jian

Hi,
Due to the limited time I have not posted yet a guide how to use it.
This python tool is a package of petrophysical functions.

One small example of "petrophysics" usage (Calculation of VSH from GR with a clavier correction) can look like:

![Capture_000](https://user-images.githubusercontent.com/17447940/227991817-5467878c-b575-4648-ad77-192ef3968607.JPG)

If this answer is satisfactory for you I am going to close this "issue".

**Comment by lj-cug** [comment]
Yes, Thank you very much!  Thanks [Philliec459](https://github.com/Philliec459), [petroGG](https://github.com/petroGG).This can guide me to use this tool.
